### ISSUE TITLE
Moscow timezone in onion.sh is incorrect

### ISSUE THREAD

**Issue by devcas** [OnionIoT/Onion-Scripts#2]
User @Alexandr-Didenko on the Onion community site has identified that the timezone value for Moscow is not UTC+4 as currently reflected in the onion.sh script and provided a [fix](https://community.onion.io/post/18722)

The error appears to be legitimately defined, since per the Wikipedia entry for [Moscow Time](https://en.wikipedia.org/wiki/Moscow_Time), "It has been set to UTC+03:00 permanently on 26 October 2014", before that date it had been set to UTC+04:00 year-round since 27 March 2011."

**Comment by greenbreakfast** [comment]
Thanks for bringing this to our attention. I've merged PR #2 and this will be included in the upcoming OpenWRT-18.06 based firmware!
